blank_issues_enabled: false
contact_links:
  - name: Domoticz Forum
    url: https://domoticz.com/forum/viewtopic.php?f=69&t=31869
    about: Join the DzGA thread in Domoticz community.
  - name: DZGA Discord Community
    url: https://discordapp.com/invite/AmJV6AC
    about: Join the Official DzGA Discord community.
